name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        java: [17-jdk]
    runs-on: ubuntu-latest
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build --stacktrace
      - uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r build.zip ./build
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version_name.outputs.version }}
          release_name: v${{ steps.extract_version_name.outputs.version }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build.zip
          asset_name: build.zip
          asset_content_type: application/zip
      
